#ifndef __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__
#define __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__

enum control_flow_type {
    CONTROL_FLOW_EMPTY,
    CONTROL_FLOW_LINEAR,
    CONTROL_FLOW_IF,
    CONTROL_FLOW_IF_ELSE,
    CONTROL_FLOW_WHILE,
    CONTROL_FLOW_DO_WHILE,
    CONTROL_FLOW_FOR,
    CONTROL_FLOW_SWITCH,
};

#endif /* __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__ */
