#ifndef __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__
#define __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__

enum control_flow_type {
    CF_EMPTY,
    CF_LINEAR,
    CF_IF,
    CF_IF_ELSE,
    CF_WHILE,
    CF_DO_WHILE,
    CF_FOR,
    CF_SWITCH,
};

#endif /* __BUILDER_CONTROL_FLOW_PATTERN_CONTROL_FLOW_TYPE_H__ */
